"""initial schema

Revision ID: 04f1229e9595
Revises: 
Create Date: 2026-07-16 17:26:26.764372+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f1229e9595'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', 'CNY', name='currency_enum'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oem_normalized', sa.String(length=128), nullable=False),
    sa.Column('oem_raw', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oem_normalized', 'brand', name='uq_parts_oem_brand')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index('ix_parts_oem_normalized', ['oem_normalized'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', 'CNY', name='currency_enum'), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'pending', name='user_role_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('column_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('oem_col', sa.String(length=255), nullable=False),
    sa.Column('brand_col', sa.String(length=255), nullable=False),
    sa.Column('name_col', sa.String(length=255), nullable=False),
    sa.Column('price_col', sa.String(length=255), nullable=False),
    sa.Column('qty_col', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='upload_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('price_rub', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_original', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', 'CNY', name='currency_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['price_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'supplier_id', name='uq_offers_part_supplier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('price_uploads')
    op.drop_table('column_mappings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('suppliers')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index('ix_parts_oem_normalized')

    op.drop_table('parts')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
